/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./*.html",
    "./pages/**/*.html",
    "./js/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#cdd4eb",
        "inverse-on-surface": "#9b9d9e",
        "on-tertiary-fixed-variant": "#006544",
        "on-secondary-fixed": "#383f51",
        "primary-fixed": "#4388fd",
        "on-background": "#2d3335",
        "on-secondary": "#f9f8ff",
        "on-tertiary-fixed": "#00452d",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#dee3e6",
        "error-container": "#fa746f",
        "tertiary-dim": "#005f40",
        "tertiary-fixed": "#69f6b8",
        "secondary-dim": "#4b5366",
        "on-secondary-container": "#4a5264",
        "outline": "#767c7e",
        "on-secondary-fixed-variant": "#545b6e",
        "on-primary-fixed": "#000000",
        "primary-dim": "#004fad",
        "on-tertiary-container": "#005a3c",
        "error": "#a83836",
        "on-primary-fixed-variant": "#001435",
        "surface-bright": "#f8f9fa",
        "surface-container-high": "#e5e9eb",
        "secondary-fixed": "#dbe2f9",
        "on-primary": "#f9f8ff",
        "surface-container-low": "#f1f4f5",
        "surface": "#f8f9fa",
        "secondary": "#575f72",
        "primary-fixed-dim": "#317bef",
        "error-dim": "#67040d",
        "primary-container": "#4388fd",
        "primary": "#005bc4",
        "secondary-container": "#dbe2f9",
        "inverse-surface": "#0c0f10",
        "tertiary-fixed-dim": "#58e7ab",
        "inverse-primary": "#4d8eff",
        "tertiary-container": "#69f6b8",
        "outline-variant": "#adb3b5",
        "surface-container": "#ebeef0",
        "surface-tint": "#005bc4",
        "on-error-container": "#6e0a12",
        "tertiary": "#006d4a",
        "on-tertiary": "#e6ffee",
        "on-primary-container": "#000311",
        "background": "#f8f9fa",
        "on-error": "#fff7f6",
        "on-surface-variant": "#5a6062",
        "surface-variant": "#dee3e6",
        "surface-dim": "#d5dbdd",
        "on-surface": "#2d3335"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}